name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    # strategy:
    #   matrix:
    #     configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      platform: win-x64
      artifact-name: windows-64-executable

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: dotnet publish ./DiskReader -r ${{ env.platform }} -c Release -o ./output

    - name: Upload
      uses: actions/upload-artifact@v4
      with: 
        path: ./output
        name: ${{ env.artifact-name }}

